### ISSUE TITLE
네이버 아이디로 로그인 하기 실패

### ISSUE THREAD

**Issue by sungjin-woo** [wonpyohong/CommunityWeb#3]
# 재현현상

네이버 아이디로 로그인을 시도할 경우,
네이버에서 로그인 후 권한을 획득하고 앱으로 돌아가면 아무런 동작을 하지 않습니다.
앱에서 다시 시도할 경우 동일한 권한 획득 화면만 나타납니다.

**Comment by wph144** [comment]
저는 테스트 폰이라 네이버 앱이 설치 안 되어 있어서 문제 없이 동작했었는데,
네이버 앱이 설치되어 있을 때 생기는 문제였습니다.
1.3.7에서 해결했습니다. 근데 1.3.7이 업로드가 30분째 안 되네요 ㅠ

**Comment by sungjin-woo** [comment]
네이버 로그인이 성공되는 것을 확인해 이슈를 닫습니다.
