### ISSUE TITLE
롱프레스 메뉴 동작 불가

### ISSUE THREAD

**Issue by sungjin-woo** [wonpyohong/CommunityWeb#5]
# 재현현상

- 롱프레스를 통해 나타난 메뉴의 동작을 할수 없음
  - 하단의 삭제/이전달/다음달/오늘 버튼을 클릭할수 없음

# 참고

- 복사 동작은 정상적임

**Comment by wph144** [comment]
아, 그건 클릭이 아니라
오늘 & 삭제 -> 드래그 앤 드랍
이전달 & 다음달 -> 1초 이상 올려놓기
로 동작하는데, 양손으로 해도 되도록 4개 다 클릭도 추가해도 넣어도 될 것 같네요.

**Comment by sungjin-woo** [comment]
아 이건 제가 UX를 이해하지 못한거니 이슈가 아닌걸로 ㅎㅎㅎ
이슈를 닫겠습니다.
